# Generated by Django 5.0.1 on 2024-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('yearofpublication', models.PositiveIntegerField()),
            ],
        ),
    ]
